---
- name: Check base image exists
  ansible.builtin.stat:
     path: "{{ ocp_iso_customize_dest }}/{{ ocp_iso_customize_source_iso_url | urlsplit('path') | basename }}"
  register: baseimage

- name: Fail if baseimage is not found
  run_once: true
  ansible.builtin.fail:
     msg: "Base image {{ ocp_iso_customize_dest }}/{{ ocp_iso_customize_source_iso_url | urlsplit('path') | basename }} not found"
  when: not baseimage.stat.exists

- name: Prompt command
  ansible.builtin.debug:
    msg: podman run --pull=always --privileged --rm -v {{ ocp_iso_customize_dest }}:/data -w /data quay.io/coreos/coreos-installer iso customize -o /data/{{ _output_iso_name }} --dest-karg-append "{{ _kargs }}" --live-karg-append "{{ _live_kargs }}" --dest-device /dev/{{ ocp_iso_customize_dest_device | default('sda') }} /data/{{ _input_iso_name }}
  when: _kargs is defined

- name: CoreOS Iso customize
  containers.podman.podman_container:
     name: customioze_iso_builder_{{ ansible_host }}
     image: "{{ ocp_iso_customize_podman_coreos_installer_image | default('quay.io/coreos/coreos-installer') }}"
     command:
        - iso
        - customize
        - --output=/data/{{ _output_iso_name }}
        - --dest-karg-append={{ _kargs }}
        - --live-karg-append={{ _live_kargs }}
        - --dest-device=/dev/{{ ocp_iso_customize_dest_device | default('sda') }}
        - /data/{{ _input_iso_name }}
     detach: false
     privileged: true
     rm: true
     volume:
        - "{{ ocp_iso_customize_dest }}:/data"
     workdir: /data
  when: _kargs is defined
