---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
  tasks:
  - name: Check resulting minimal iso
    ansible.builtin.find:
      path: "/var/www/html/example/images/coreOS"
      pattern: "minimal-*.iso"
      excludes: "*fedora*"
    register: results

  - name: Debug find
    ansible.builtin.debug:
      msg: "{{ results }}"
      verbosity: 3

  - name: Verify minify results
    ansible.builtin.fail:
      msg: "FAILURE - error in iso count - should have bootstrap, controler and worker"
    when: results.matched != 1
