---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: bootstrap
    image: quay.io/fedora/fedora:37
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - bootstrap
  - name: controler
    image: quay.io/fedora/fedora:38
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - controlers
  - name: worker01
    image: quay.io/fedora/fedora:39
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - workers
provisioner:
  name: ansible
  log: false
  options:
    v: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
